framework:
  default_locale: '%env(default:LOCALIZING_DEFAULT_LOCALE:APP_LOCALE)%'
  translator:
    default_path: '%kernel.project_dir%/translations'
    fallbacks:
      - '%env(default:LOCALIZING_FALLBACK_LOCALE:APP_FALLBACK_LOCALE)%'
