localizing_api_locale_list:
  path: /api/locale
  controller: App\Localizing\Controller\Api\LocaleApiController::__invoke
  methods: [GET]

localizing_api_locale_fallback:
  path: /api/locale/fallback/{slug}
  controller: App\Localizing\Controller\Api\LocaleFallbackApiController::__invoke
  methods: [GET]

localizing_api_translation_domain_list:
  path: /api/locale/translation/domain
  controller: App\Localizing\Controller\Api\LocaleTranslationDomainApiController::__invoke
  methods: [GET]

localizing_api_translation_key_list:
  path: /api/locale/translation/key
  controller: App\Localizing\Controller\Api\LocaleTranslationKeyApiController::__invoke
  methods: [GET]

localizing_api_translation_message_resolve:
  path: /api/locale/translation/message/resolve
  controller: App\Localizing\Controller\Api\LocaleTranslationMessageApiController::resolve
  methods: [GET]

localizing_api_terminology_list:
  path: /api/locale/terminology
  controller: App\Localizing\Controller\Api\LocaleTerminologyApiController::__invoke
  methods: [GET]
