parameters:
  localizing.default_locale: 'en'
  localizing.supported_locales:
    - 'en'
    - 'uk'
    - 'ru'
  localizing.catalog_source_dir: '%kernel.project_dir%/resources/catalogs'
  localizing.catalog_export_dir: '%kernel.project_dir%/var/export/translations'

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/'

  App\Service\Locale\LocaleRegistry:
    arguments:
      $configuredLocales: '%localizing.supported_locales%'
      $defaultLocaleCode: '%localizing.default_locale%'

  App\Service\Catalog\LocaleFilesystemCatalogScanner:
    arguments:
      $catalogDirectory: '%localizing.catalog_source_dir%'

  App\Service\Catalog\LocaleSymfonyCatalogExporter:
    arguments:
      $exportDirectory: '%localizing.catalog_export_dir%'

  App\ServiceInterface\Catalog\LocaleCatalogScannerInterface: '@App\Service\Catalog\LocaleFilesystemCatalogScanner'
  App\ServiceInterface\Catalog\LocaleCatalogExporterInterface: '@App\Service\Catalog\LocaleSymfonyCatalogExporter'
  App\ServiceInterface\Quality\LocaleCatalogAuditorInterface: '@App\Service\Quality\LocaleCatalogAuditor'
  App\ServiceInterface\Locale\LocaleCodeNameConverterInterface: '@App\Service\Locale\LocaleCodeNameConverter'
  App\ServiceInterface\Locale\LocaleFallbackResolverInterface: '@App\Service\Locale\LocaleFallbackResolver'
  App\ServiceInterface\Locale\LocaleRegistryInterface: '@App\Service\Locale\LocaleRegistry'
  App\ServiceInterface\Template\LocaleTemplateSelectorProviderInterface: '@App\Service\Template\LocaleTemplateSelectorProvider'
  App\ServiceInterface\Template\LocaleTemplateContextProviderInterface: '@App\Service\Template\LocaleTemplateContextProvider'
